name: Build and Push Frontend Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Bump Version and Push Tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v5
              with:
                github_token: ${{ secrets.PAT }}
        
            - name: Create a GitHub Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.PAT }}
              with:
                tag_name: ${{ steps.tag_version.outputs.new_tag }}
                release_name: Release ${{ steps.tag_version.outputs.new_tag }}
                body: ${{ steps.tag_version.outputs.changelog }}
            
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/azure_frontend:${{ steps.tag_version.outputs.new_tag }}

            - name: Restart Docker container
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd vm
                    sudo docker-compose down
                    sudo docker-compose pull
                    # sudo snap install jq
                    export BACKEND_TAG=$(curl -s "https://hub.docker.com/v2/repositories/suahcho/azure_backend/tags/?page_size=1&ordering=last_updated" | jq -r '.results[0].name')
                    export FRONTEND_TAG=$(curl -s "https://hub.docker.com/v2/repositories/suahcho/azure_frontend/tags/?page_size=1&ordering=last_updated" | jq -r '.results[0].name')
                    sudo BACKEND_TAG=$BACKEND_TAG FRONTEND_TAG=$FRONTEND_TAG docker-compose up -d

            